### ISSUE TITLE
输出的文件名为*.out.logit 

### ISSUE THREAD

**Issue by ningyuwhut** [chengstone/kaggle_criteo_ctr_challenge-#1]
在FFM 那里， 输出的文件名为*.out.logit 
===
但是命令里面并没有指定是out.logit,我在libFFM的文档里面也没有找到相关的信息，请问是哪里指定了输出文件名是.out.logit  呢 另外*.out.logit文件里面记录的是什么呢，和*.out什么区别呢

谢谢！

**Comment by chengstone** [comment]
*.out.logit文件和文件中的内容请阅读项目中libFFM的代码，我做了修改。
