### ISSUE TITLE
gbdt的叶子节点作为fm的输入

### ISSUE THREAD

**Issue by ningyuwhut** [chengstone/kaggle_criteo_ctr_challenge-#2]
有个问题请教下，
文章关于使用GBDT的叶子节点作为FM的输入:
GBDT已经训练好了，我们需要GBDT输出的叶子节点作为输入数据X传给FM，一共30个叶子节点，那么输入给FM的数据格式就是X中不是0的数据的index:value。

但是我看代码里面好像是把gbdt的每棵树的输出作为FM的输入的。

因为lightgbm中的树个数是32，叶子节点是30，如果是叶子节点的输出作为FM的输入的话，那FM的输入维度应该是30，而不是32。不知道是不是我理解的有问题。

另外，在计算FM的输入时代码如下:

 for i in range(tree_counts):
                    train_leaves[:, i] = train_leaves[:, i] + tree_info[i]['num_leaves'] * i + 1
                    valid_leaves[:, i] = valid_leaves[:, i] + tree_info[i]['num_leaves'] * i + 1
                    test_leaves[:, i] = test_leaves[:, i] + tree_info[i]['num_leaves'] * i + 1

这段代码该如何理解呢，为什么每棵树的输出都要加上“tree_info[i]['num_leaves'] * i + 1” 呢

多谢

**Comment by chengstone** [comment]
训练的GBDT一共32棵树，每棵树30个叶子节点，相同的输入，每棵树都会有一个结果，这个结果对应了30个叶子节点中的一个，所以维度是32。
另外，gbm.predict(。。。, pred_leaf=True)，你可以看到参数pred_leaf是True，所以输出的是叶子节点。
加上“tree_info[i]['num_leaves'] * i + 1” 是因为每棵树都是30个叶子节点中的一个，我们需要这些值统一编号，而不是互相独立，比如：
26， 22， 30，这不是我们想要的。
应该是26，48，78 。
看下面这个真实数据的样子：
0 0:31 1:61 2:93 3:108 4:149 5:182 6:212 7:242 8:277 9:310 10:334 11:365 12:401 13:434 14:465 15:491 16:527 17:552 18:589 19:619 20:648 21:678 22:697 23:744 24:770 25:806 26:826 27:862 28:899 29:928 30:955 31:988

**Comment by supersush** [comment]
您好，关于gbdt输出的问题，输出的是tree_index:leaf_index。我理解这个更像是个类别特征，比如数据归到的第n颗树的第m个叶子节点。直接将tree_index:leaf_index作为fm的输入感觉比较费解。既然您已经将leaf_index进行统一编号了，是不是将leaf_index:1 这种类别特征的数据输入更合理呢？

**Comment by supersush** [comment]
您好，关于gbdt输出的问题，输出的是tree_index:leaf_index。
我理解这更像是个类别特征而不是数值特征，比如数据归到的第n颗树的第m个叶子节点。
直接将tree_index:leaf_index作为fm的输入我不太理解。既然您已经将leaf_index进行统一编号了，是不是将leaf_index:1 作为类别特征 输入到fm更合适呢？
谢谢
